### ISSUE TITLE
Date on events page is always one day less

### ISSUE THREAD

**Issue by sandeepyadavm** [YogeshNaikZionTech/charityfoundation#71]
While creating an event on admin page, In database date is store is perfectly alright. But on the UI it show a day behind. Please look in to it.

**Comment by kimsuka** [comment]
This happens when there is no TimeZone specified. JavaScript will assume the time is in GMT and display the date & time wrt your local TimeZone. I have fixed this is in the UI (not pushed yet) by making it assume the date is always in PST but a better solution would be to specify the timezone during event creation.

**Comment by kimsuka** [comment]
This is done but I'm leaving it open because I would like to discuss a better solution.

**Comment by YogeshNaikZionTech** [comment]
Yogesh to confirm about Event locations with Ashok.

**Comment by kimsuka** [comment]
Done assuming time entered during creation is always in IST.
